CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255)  NOT NULL,
    password_hash VARCHAR(255)  NOT NULL,
    role          VARCHAR(20)   NOT NULL,
    profile_status VARCHAR(20)  NOT NULL,
    account_status VARCHAR(20)  NOT NULL,

    first_name    VARCHAR(100),
    last_name     VARCHAR(100),
    birth_date    DATE,
    gender        VARCHAR(20),
    bio           VARCHAR(1000),

    version       BIGINT        NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT users_role_check
        CHECK (role IN ('USER', 'ADMIN')),

    CONSTRAINT users_profile_status_check
        CHECK (profile_status IN ('PENDING', 'ACTIVE')),

    CONSTRAINT users_account_status_check
        CHECK (account_status IN ('ACTIVE', 'BLOCKED')),

    CONSTRAINT users_gender_check
        CHECK (gender IS NULL OR gender IN ('MALE', 'FEMALE', 'OTHER')),

    CONSTRAINT users_birth_date_check
        CHECK (birth_date IS NULL OR birth_date < CURRENT_DATE)
);

CREATE UNIQUE INDEX users_email_unique_idx
    ON users (LOWER(email));
