CREATE TABLE REACTIONS
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id     BIGINT      NOT NULL,
    receiver_id   BIGINT      NOT NULL,
    reaction_type VARCHAR(20) NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT reactions_sender_fk
        FOREIGN KEY (sender_id)
            REFERENCES users (id)
            ON DELETE CASCADE,

    CONSTRAINT reactions_receiver_fk
        FOREIGN KEY (receiver_id)
            REFERENCES users (id)
            ON DELETE CASCADE,

    CONSTRAINT reactions_sender_receiver_unique
        UNIQUE (sender_id, receiver_id),

    CONSTRAINT reactions_no_self_reaction
        CHECK (sender_id <> receiver_id),

    CONSTRAINT reactions_type_check
        CHECK (reaction_type IN ('LIKE', 'PASS'))
);

CREATE INDEX reactions_receiver_id_idx
    ON reactions (receiver_id);