CREATE TABLE user_photos
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    object_key VARCHAR(500) NOT NULL,
    position   INTEGER      NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT user_photos_user_fk
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE,

    CONSTRAINT user_photos_object_key_unique
        UNIQUE (object_key),

    CONSTRAINT user_photos_position_non_negative
        CHECK (position >= 0),

    CONSTRAINT user_photos_user_position_unique
        UNIQUE (user_id, position)
);

CREATE INDEX user_photos_user_id_idx
    ON user_photos (user_id);
